### ISSUE TITLE
有几个疑问！

### ISSUE THREAD

**Issue by OffroadOps** [easy-do/dnf-admin#1]
1.https://sa-token.cc (v1.37.0)
SA [INFO] -->: 全局配置 SaTokenConfig [tokenName=Authorization, timeout=3600, activeTimeout=-1, dynamicActiveTimeout=false, isConcurrent=false, isShare=true, maxLoginCount=12, maxTryTimes=12, isReadBody=true, isReadHeader=true, isReadCookie=true, isWriteHeader=false, tokenStyle=tik, dataRefreshPeriod=30, tokenSessionCheckLogin=true, autoRenew=true, tokenPrefix=null, isPrint=true, isLog=true, logLevel=trace, logLevelInt=1, isColorLog=true, jwtSecretKey=0d494aec-f476-4630-9c2c-23495d2eb410, basic=, currDomain=null, sameTokenTimeout=86400, checkSameToken=false, cookie=SaCookieConfig [domain=null, path=null, secure=false, httpOnly=false, sameSite=null], sign=SaSignConfig [secretKey=null, timestampDisparity=900000, isCheckNonce=true]] 
SA [INFO] -->: 全局组件 StpInterface 载入成功: plus.easydo.dnf.config.StpInterfaceImpl
SA [INFO] -->: 全局组件 SaTokenContext 载入成功: cn.dev33.satoken.spring.SaTokenContextForSpringInJakartaServlet
SA [INFO] -->: 全局组件 SaJsonTemplate 载入成功: cn.dev33.satoken.spring.json.SaJsonTemplateForJackson
SA [INFO] -->: 会话组件 StpLogic(type=login) 重置成功: class cn.dev33.satoken.jwt.StpLogicJwtForSimple
2023-11-30T19:04:34.380+08:00  INFO 1 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
2023-11-30T19:04:34.441+08:00  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8888 (http) with context path ''
2023-11-30T19:04:34.452+08:00  INFO 1 --- [           main] plus.easydo.dnf.DnfAdminApplication      : Started DnfAdminApplication in 5.325 seconds (process running for 5.646)
2023-11-30T19:04:34.458+08:00  INFO 1 --- [           main] p.e.d.s.impl.DaGameConfigServiceImpl     : 初始化缓存游戏配置 start
2023-11-30T19:04:34.507+08:00  INFO 1 --- [           main] mybatis-flex-sql                         : SELECT `id`, `conf_name`, `conf_type`, `conf_data`, `conf_key`, `remark` FROM `da_game_config`,8ms
2023-11-30T19:04:34.508+08:00  INFO 1 --- [           main] p.e.d.s.impl.DaGameConfigServiceImpl     : 初始化缓存游戏配置 end
2023-11-30T19:04:34.509+08:00  INFO 1 --- [           main] p.easydo.dnf.runner.MyApplicationRunner  : 复制dp2插件

一个小时了还在复制 不知道什么情况？

第二个问题

DNFServer 启动 日志 

[!] Init DataManager Success
[!] Init GameManager ...
[!] Init GameManager Success
[!] Init Arad GameScriptManager ...
[!] Loading CeraShop Add Restrict Type script - Success
	- Loading Levelup Support Event script - Success
	- Loading EventCreateDnf script - Success
	- Loading Avatar Hidden Option - Success
	- Loading Avatar Recharge script - Success
	- Loading Emblem Compound script - Success
	- Loading Event Period Script - Success
	- Loading Statistics Item List - Success
	- Loading NexonFolder Script - Success
	- Loading Avatar Convert script - Success
	- Loading Level Up Support 2nd Event script - Success
[!] Init Arad GameScriptManager Success
[!] Init ChannelType Success
	- Channel Type : 13
[!] Init tournament db Success
[!] Connect To Monitor Server ... 
[!] Connect To Guild Server ...
[!] Init GameWorld ../../Include/FilePack/Pack.cpp(819) - get
../../Include/FilePack/Pack.cpp(819) - get
../../Include/FilePack/Pack.cpp(819) - get
../../Include/FilePack/Pack.cpp(819) - get
../../Include/FilePack/Pack.cpp(819) - get
../../Include/FilePack/Pack.cpp(819) - get

一直是这样！ 啥情况？ 

当前内存信息

root@rdns:~/dnf-admin# free -m
               total        used        free      shared  buff/cache   available
Mem:            3914        3781         121         179         410         132
Swap:           8191        2479        5712

**Comment by easy-do** [comment]
首先第一个没问题，只是没做复制结束的日志打印，属于正常启动，第二个问题没遇到过，可是重启试试，一般来说只要是x86centos或者ubuntu的机器都能正常跑服务端

**Comment by OffroadOps** [comment]
其实你都使用docker-compose了  我肯定使用我擅长的系统 我目前系统是 Debian12 当前启动后的情况是
[!] Init Arad GameScriptManager Success
[!] Init ChannelType Success
      - Channel Type : 13
[!] Init tournament db Success
[!] Connect To Monitor Server ...
[!] Connect To Guild Server ...
[!] Init GameWorld ../../Include/FilePack/Pack.cpp(819) - get
../../Include/FilePack/Pack.cpp(819) - get
../../Include/FilePack/Pack.cpp(819) - get
../../Include/FilePack/Pack.cpp(819) - get
../../Include/FilePack/Pack.cpp(819) - get
../../Include/FilePack/Pack.cpp(819) - get
../.
**********************************************************
* +---   +-+ +  +----         DUNGEON & FIGHTER          *
* |   |  | | |  |                                        *
* |   |  | | |  +----                                    *
* |   |  | | |  |      Open Beta Test on 2005.08.10~     *
* +---   + +-+  |      Copyright(c) 2004,2005 Neople Co. *
**********************************************************
[!] Service Date (23-11-30/19:20)
Application Init() Success!
Application Load() Success!
Hook select
---Time : 19, 21 ----
avgPing(0, 0, 0)
avgPing Res(0)
avgPing(0, 0, 0)
avgPing Res(0)
---Time : 19, 22 ----
avgPing(0, 0, 0)
avgPing Res(0)
avgPing(0, 0, 0)
avgPing Res(0)

我感觉这个和系统似乎没啥关系 运行的程序是跑在Docker里面的！ 顺便问下大佬有联系方式吗？
________________________________
发件人: 隔壁老于 ***@***.***>
发送时间: 2023年11月30日 12:37
收件人: easy-do/dnf-admin ***@***.***>
抄送: dahai0401 ***@***.***>; Author ***@***.***>
主题: Re: [easy-do/dnf-admin] 有几个疑问！ (Issue #1)


首先第一个没问题，只是没做复制结束的日志打印，属于正常启动，第二个问题没遇到过，可是重启试试，一般来说只要是x86centos或者ubuntu的机器都能正常跑服务端

**Comment by easy-do** [comment]
服务端最佳搭配是centos7系，debain目前我这里没见人跑过，所以猜测是系统内核兼容性问题，联系进群：418505204

**Comment by easy-do** [comment]
close
