### ISSUE TITLE
dnfadmin的数据库密码是不是没读取到env

### ISSUE THREAD

**Issue by ClayWangT** [easy-do/dnf-admin#2]
只改了一个MYSQL_ROOT_PASSWORD
dnfadmin就报错连不上数据库

java.sql.SQLException: Access denied for user 'root'@'172.20.0.4' (using password: YES)

**Comment by ClayWangT** [comment]
windows11环境，用默认的88888888就没事

**Comment by easy-do** [comment]
两个指定root密码的地方都要改，一个是设置数据库密码，一个是告诉后台数据库密码是啥

**Comment by ClayWangT** [comment]
> 两个指定root密码的地方都要改，一个是设置数据库密码，一个是告诉后台数据库密码是啥

ok 懂了
